### ISSUE TITLE
Add snap package to snapcraft.io

### ISSUE THREAD

**Issue by bamps** [webtorrent/.github#2] opened 2020-05-17 15:23 UTC
I'm using Ubuntu.
Latest OS versions have snap store on https://snapcraft.io/first-snap.
Is it possible to create webtorrent desktop packages for it?

**Comment by alxhotel** [comment] 2020-05-17 15:35
Duplicate of webtorrent/webtorrent-desktop#1071

Hi @bamps, thanks for the question. Please check out the comments in the referenced issue,

**Closed as completed by alxhotel** 2020-05-17 15:35 UTC
